config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: Settings.max_length_name }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: Settings.max_length_email }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: Settings.min_length_pass }
  private
  def email_downcase
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    private

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home;  end

  def help;  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "rails"
    page_title.empty? ? base_title : page_title + "|" + base_title
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t "rail", "https://www.railstutorial.org/" %> by <%= link_to t "michael", "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t "about",   about_path %></li>
      <li><%= link_to t "contact", contact_path %></li>
      <li><%= link_to t "news", "http://news.railstutorial.org/" %>S</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the t "rail" at the
  <%= link_to t "help", "http://www.railstutorial.org/help" %>.
  To get help on this sample app, see the
  <%= link_to "<em>t "rail"</em> book", "http://www.railstutorial.org/book".
</p>
<%= link_to "English", locale:"en" %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>t "welcome"</h1>
  <h2>
    This is the home page for the
    <%= link_to t "ruby", "https://www.railstutorial.org/" %>
    sample application.
  </h2>

  <%= link_to t "now", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), "http://rubyonrails.org/" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>